### ISSUE TITLE
Kirby Takes Center Stage

### ISSUE THREAD

**Issue by LibereMei** [Dietlofmeyer/gamershaven#5]
Once registered I was not able to see my profile because there was a HUGE Kirby graphic covering everything.

![image](https://github.com/Dietlofmeyer/gamershaven/assets/171575055/93e84ab6-c9dc-4b3a-a4d9-412e57802596)

**Comment by Dietlofmeyer** [comment]
Hello LibereMei. Thank you so much for your feedback, I'm sorry that you're not able to view your profile page due to our big pink balloon covering everything. As character that lives off eating almost everything it sees, it might have just over-inflated a bit. I have temporarily removed the image from the page, you should be able to see everything now. Kirby won't be gone for too long, it should be back soon and smaller.
